### ISSUE TITLE
Vuex-cache for Nuxtjs -> Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by standfv** [superwf/vuex-cache#36] opened 2019-03-28 02:50 UTC
I'm did read docs.
I'm create plugins/vuex-cache.js
End config nuxt.config.js

I use this.$store.cache.dispatch("modulesA/actionA") in folder components.
F5 router => alert " Cannot read property 'dispatch' of undefined"
? How to fix?

**Comment by VitorLuizC** [comment] 2019-04-09 07:12
Maybe this is happening before `onNuxtReady`.

Can you provide a project on CodeSandbox or a repository to reproduce this bug?

**Comment by VitorLuizC** [comment] 2019-07-24 14:18
I couldn't reproduce this issue, so I'm closing it.

**Closed by VitorLuizC** 2019-07-24 14:18 UTC

**Comment by leeovery** [comment] 2019-08-22 10:16
Im getting the same issue here

**Comment by VitorLuizC** [comment] 2019-08-22 14:45
@leeovery Can you provide a project on CodeSandbox or a repository to reproduce this bug?

**Comment by baumak** [comment] 2021-06-17 15:16
use it like usual nuxt vuex store plugin 
https://nuxtjs.org/docs/2.x/directory-structure/store#plugins-in-the-store
 
In Nuxt i did like this below
in store/index.js 
`
import createCache from 'vuex-cache'; `
`const options = {
          timeout: 30000 // Equal to 30 seconds in milliseconds.
      };`
`export const plugins = [createCache(options)] `
